- name: '[Docker] | check docker status'
  command: docker --version
  register: docker_version

- name: '[Docker] | download install script'
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: u+rx
  when: docker_version.stdout.find('version') != 1

- name: '[Docker] | run install script'
  shell: /tmp/get-docker.sh
  when: docker_version.stdout.find('version') != 1

- name: '[Docker] | add user to docker group'
  command: usermod -aG docker {{user}}